import uuid
from datetime import datetime, timezone
from app.schemas.twin import (
    Asset,
    AssetType,
    ZoneType,
    CriticalityLevel,
    Identity,
    PrivilegeLevel,
    CredentialState,
    Relationship,
    RelationshipType,
    SecurityControl,
    Vulnerability,
    DigitalTwinTopology,
)


def create_demo_topology() -> DigitalTwinTopology:
    """Generate the flagship 12-node Enterprise Cyber War Room topology."""
    now = datetime.now(timezone.utc).isoformat()

    # 1. Vulnerabilities
    vuln_log4j = Vulnerability(
        cve="CVE-2021-44228",
        name="Apache Log4j RCE (Log4Shell)",
        severity=CriticalityLevel.CRITICAL,
        cvss_score=10.0,
        affected_service="Java Application Gateway :8080",
        exploitable_technique="T1190",
        patch_available=True,
        description="JNDI lookup injection allows unauthenticated remote code execution.",
    )
    vuln_vpn = Vulnerability(
        cve="CVE-2024-21887",
        name="Ivanti Connect Secure Command Injection",
        severity=CriticalityLevel.CRITICAL,
        cvss_score=9.8,
        affected_service="SSL-VPN Web Interface :443",
        exploitable_technique="T1190",
        patch_available=True,
        description="Command injection in web components allows arbitrary command execution as root.",
    )
    vuln_zerologon = Vulnerability(
        cve="CVE-2020-1472",
        name="Netlogon Elevation of Privilege (ZeroLogon)",
        severity=CriticalityLevel.CRITICAL,
        cvss_score=10.0,
        affected_service="Netlogon RPC :445",
        exploitable_technique="T1068",
        patch_available=True,
        description="Flaw in Netlogon cryptographic protocol allows unauthenticated DC takeover.",
    )
    vuln_sqli = Vulnerability(
        cve="CVE-2023-38606",
        name="Customer Portal SQL Injection",
        severity=CriticalityLevel.HIGH,
        cvss_score=8.6,
        affected_service="Public Web Application :443",
        exploitable_technique="T1190",
        patch_available=False,
        description="Unsanitized query parameters allow extraction of internal database records.",
    )

    # 2. Controls
    ctrl_edr_fleet = SecurityControl(
        id="CTRL-EDR-01",
        name="CrowdStrike EDR Agent Fleet",
        type="EDR",
        description="Behavioral endpoint detection and response on all corporate workstations.",
        is_active=True,
        coverage_scope=["WS-ENG-04", "WS-FIN-02", "APP-SRV-01"],
        effectiveness=0.88,
    )
    ctrl_waf = SecurityControl(
        id="CTRL-WAF-01",
        name="Cloudflare Web Application Firewall",
        type="WAF",
        description="Inspects incoming HTTPS traffic for OWASP Top 10 exploits.",
        is_active=True,
        coverage_scope=["WEB-SRV-01"],
        effectiveness=0.85,
    )
    ctrl_mfa_corp = SecurityControl(
        id="CTRL-MFA-CORP",
        name="FIDO2 / TOTP Multi-Factor Authentication",
        type="MFA",
        description="Enforced on VPN and External portals, but NOT internal Kerberos/SMB pivots.",
        is_active=True,
        coverage_scope=["VPN-GW-01", "WEB-SRV-01"],
        effectiveness=0.95,
    )
    ctrl_vault_airgap = SecurityControl(
        id="CTRL-VAULT-ISOLATE",
        name="Immutable Backup Storage Air-Gap",
        type="NETWORK_SEGMENTATION",
        description="Restricts network access to backup vaults to dedicated backup windows only.",
        is_active=False,  # Initially disabled! Enabled in Defense Sandbox!
        coverage_scope=["VAULT-BACKUP-01"],
        effectiveness=0.98,
    )

    # 3. Assets
    assets = [
        Asset(
            id="EXT-INTERNET",
            name="External Internet Adversary Space",
            type=AssetType.ROUTER,
            zone=ZoneType.INTERNET,
            criticality=CriticalityLevel.LOW,
            ip_address="198.51.100.1",
            os="Routing Edge",
            department="External",
            services=["BGP", "DNS"],
            criticality_score=1.0,
        ),
        Asset(
            id="FW-EDGE-01",
            name="Perimeter NextGen Firewall",
            type=AssetType.FIREWALL,
            zone=ZoneType.DMZ,
            criticality=CriticalityLevel.HIGH,
            ip_address="203.0.113.1",
            os="Palo Alto PAN-OS",
            department="Infrastructure Security",
            services=["HTTPS :443", "IPSec :500"],
            controls=["CTRL-MFA-CORP"],
            criticality_score=7.0,
        ),
        Asset(
            id="WEB-SRV-01",
            name="Public Customer Portal (DMZ)",
            type=AssetType.APPLICATION_SERVER,
            zone=ZoneType.DMZ,
            criticality=CriticalityLevel.HIGH,
            ip_address="192.168.10.15",
            os="Ubuntu Linux 22.04",
            department="Digital Operations",
            services=["Nginx :443", "Node.js :3000"],
            vulnerabilities=[vuln_sqli],
            controls=["CTRL-WAF-01"],
            criticality_score=7.5,
        ),
        Asset(
            id="VPN-GW-01",
            name="Corporate SSL-VPN Concentrator",
            type=AssetType.VPN_GATEWAY,
            zone=ZoneType.DMZ,
            criticality=CriticalityLevel.HIGH,
            ip_address="192.168.10.5",
            os="Ivanti ICS Appliance",
            department="IT Infrastructure",
            services=["SSL-VPN :443"],
            vulnerabilities=[vuln_vpn],
            controls=["CTRL-MFA-CORP"],
            criticality_score=8.0,
        ),
        Asset(
            id="WS-ENG-04",
            name="Senior DevOps Engineer Laptop",
            type=AssetType.WORKSTATION,
            zone=ZoneType.CORPORATE_LAN,
            criticality=CriticalityLevel.MEDIUM,
            ip_address="10.100.4.45",
            os="Windows 11 Enterprise",
            department="Engineering",
            services=["SSH Client", "Docker Desktop", "RDP :3389"],
            controls=["CTRL-EDR-01"],
            identities=["ID-ENG-DEV"],
            criticality_score=5.5,
        ),
        Asset(
            id="WS-FIN-02",
            name="Finance Lead Workstation",
            type=AssetType.WORKSTATION,
            zone=ZoneType.CORPORATE_LAN,
            criticality=CriticalityLevel.MEDIUM,
            ip_address="10.100.2.22",
            os="Windows 11 Enterprise",
            department="Finance",
            services=["Office 365", "ERP Client"],
            controls=["CTRL-EDR-01"],
            identities=["ID-FIN-LEAD"],
            criticality_score=5.0,
        ),
        Asset(
            id="APP-SRV-01",
            name="Core Banking & API Microservice",
            type=AssetType.APPLICATION_SERVER,
            zone=ZoneType.MANAGEMENT,
            criticality=CriticalityLevel.HIGH,
            ip_address="10.200.1.10",
            os="Red Hat Enterprise Linux 9",
            department="Core Platform",
            services=["Java SpringBoot :8080", "SSH :22"],
            vulnerabilities=[vuln_log4j],
            controls=["CTRL-EDR-01"],
            identities=["ID-SVC-APP"],
            criticality_score=8.5,
        ),
        Asset(
            id="DC-CORP-01",
            name="Corporate Active Directory Domain Controller",
            type=AssetType.DOMAIN_CONTROLLER,
            zone=ZoneType.SECURE_TIER,
            criticality=CriticalityLevel.CRITICAL,
            ip_address="10.200.0.1",
            os="Windows Server 2022 Datacenter",
            department="Enterprise Identity",
            services=["Kerberos :88", "LDAP :389", "SMB :445", "DNS :53"],
            vulnerabilities=[vuln_zerologon],
            identities=["ID-DOMAIN-ADMIN"],
            criticality_score=10.0,
        ),
        Asset(
            id="DB-PROD-01",
            name="Primary Customer Financial Database",
            type=AssetType.DATABASE,
            zone=ZoneType.SECURE_TIER,
            criticality=CriticalityLevel.CRITICAL,
            ip_address="10.200.2.50",
            os="Oracle Enterprise Linux 8",
            department="Data Platform",
            services=["PostgreSQL :5432", "Oracle TNS :1521"],
            identities=["ID-DBA-ROOT"],
            criticality_score=9.5,
        ),
        Asset(
            id="VAULT-BACKUP-01",
            name="Immutable Ransomware Backup Repository",
            type=AssetType.BACKUP_SERVER,
            zone=ZoneType.BACKUP_VAULT,
            criticality=CriticalityLevel.CRITICAL,
            ip_address="10.250.99.10",
            os="Hardened Veeam Linux Appliance",
            department="Disaster Recovery",
            services=["Veeam Data Mover :6160", "SSH :22"],
            controls=["CTRL-VAULT-ISOLATE"],
            identities=["ID-BACKUP-OPERATOR"],
            criticality_score=10.0,
        ),
        Asset(
            id="CLOUD-K8S-01",
            name="AWS Production EKS Cluster",
            type=AssetType.CLOUD_INSTANCE,
            zone=ZoneType.CLOUD_VPC,
            criticality=CriticalityLevel.HIGH,
            ip_address="172.16.0.4",
            os="Amazon Linux 2023",
            department="Cloud Engineering",
            services=["Kubernetes API :6443", "Envoy Ingress :443"],
            criticality_score=8.0,
        ),
        Asset(
            id="SIEM-SOC-01",
            name="Security Operations Monitoring & SOAR",
            type=AssetType.SERVER,
            zone=ZoneType.MANAGEMENT,
            criticality=CriticalityLevel.MEDIUM,
            ip_address="10.200.5.10",
            os="Ubuntu 22.04 LTS",
            department="Cyber Defense",
            services=["Elasticsearch :9200", "Syslog :514"],
            criticality_score=6.0,
        ),
    ]

    # 4. Identities
    identities = [
        Identity(
            id="ID-ENG-DEV",
            name="Rahul Sharma (Senior DevOps)",
            type="USER",
            role="DevOps Engineer",
            privilege_level=PrivilegeLevel.LOCAL_ADMIN,
            accessible_assets=["WS-ENG-04", "APP-SRV-01", "CLOUD-K8S-01"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["PASSWORD", "SSH_KEY"],
            mfa_enabled=False,  # Vulnerable to credential theft!
        ),
        Identity(
            id="ID-FIN-LEAD",
            name="Ananya Iyer (Finance VP)",
            type="USER",
            role="Finance Approver",
            privilege_level=PrivilegeLevel.STANDARD,
            accessible_assets=["WS-FIN-02"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["PASSWORD"],
            mfa_enabled=True,
        ),
        Identity(
            id="ID-SVC-APP",
            name="svc_banking_core",
            type="SERVICE_ACCOUNT",
            role="Application Microservice",
            privilege_level=PrivilegeLevel.ELEVATED,
            accessible_assets=["APP-SRV-01", "DB-PROD-01"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["KERBEROS_KEYTAB", "CERTIFICATE"],
            mfa_enabled=False,
        ),
        Identity(
            id="ID-DOMAIN-ADMIN",
            name="vikram.admin (Enterprise Admin)",
            type="ADMIN",
            role="Tier-0 Domain Administrator",
            privilege_level=PrivilegeLevel.DOMAIN_ADMIN,
            accessible_assets=["DC-CORP-01", "APP-SRV-01", "WS-ENG-04", "WS-FIN-02", "VAULT-BACKUP-01"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["PASSWORD", "KERBEROS"],
            mfa_enabled=False,  # Critical flaw: Domain Admin lacks internal MFA enforcement!
        ),
        Identity(
            id="ID-DBA-ROOT",
            name="dba_master",
            type="ADMIN",
            role="Database Administrator",
            privilege_level=PrivilegeLevel.ELEVATED,
            accessible_assets=["DB-PROD-01"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["PASSWORD"],
            mfa_enabled=True,
        ),
        Identity(
            id="ID-BACKUP-OPERATOR",
            name="svc_backup_agent",
            type="SERVICE_ACCOUNT",
            role="Backup & Recovery Agent",
            privilege_level=PrivilegeLevel.SYSTEM,
            accessible_assets=["VAULT-BACKUP-01", "DB-PROD-01", "APP-SRV-01"],
            credential_state=CredentialState.ACTIVE,
            auth_methods=["CERTIFICATE"],
            mfa_enabled=False,
        ),
    ]

    # 5. Relationships
    relationships = [
        # External -> Edge
        Relationship(
            id="REL-01",
            source_id="EXT-INTERNET",
            target_id="FW-EDGE-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=443,
        ),
        Relationship(
            id="REL-02",
            source_id="FW-EDGE-01",
            target_id="WEB-SRV-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=443,
        ),
        Relationship(
            id="REL-03",
            source_id="FW-EDGE-01",
            target_id="VPN-GW-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=443,
        ),
        # DMZ Web Portal -> Core App Server (API communication)
        Relationship(
            id="REL-WEB-APP",
            source_id="WEB-SRV-01",
            target_id="APP-SRV-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=8080,
            properties={"service": "REST API Gateway"},
        ),
        # Finance Workstation -> Core App Server (Internal Web Portal)
        Relationship(
            id="REL-FIN-APP",
            source_id="WS-FIN-02",
            target_id="APP-SRV-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=443,
            properties={"service": "Internal Banking Web UI"},
        ),
        # VPN -> Corp LAN & Engineering
        Relationship(
            id="REL-04",
            source_id="VPN-GW-01",
            target_id="WS-ENG-04",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=3389,
            properties={"auth": "Single Factor fallback"},
        ),
        # Workstation Lateral Reachability
        Relationship(
            id="REL-05",
            source_id="WS-ENG-04",
            target_id="APP-SRV-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=22,
        ),
        Relationship(
            id="REL-06",
            source_id="WS-ENG-04",
            target_id="DC-CORP-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=445,
            properties={"service": "SMBv2 / RPC"},
        ),
        # Credential Caching on Workstation (Huge attack vector!)
        Relationship(
            id="REL-CRED-01",
            source_id="WS-ENG-04",
            target_id="DC-CORP-01",
            type=RelationshipType.CREDENTIAL_ACCESS,
            properties={"cached_identity": "ID-DOMAIN-ADMIN", "store": "LSASS Memory / NTLM Hash"},
        ),
        # App Server to Database
        Relationship(
            id="REL-07",
            source_id="APP-SRV-01",
            target_id="DB-PROD-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=5432,
        ),
        Relationship(
            id="REL-08",
            source_id="APP-SRV-01",
            target_id="DC-CORP-01",
            type=RelationshipType.AUTHENTICATION,
            protocol="TCP",
            port=88,
            properties={"mechanism": "Kerberos TGT"},
        ),
        # DC to All Core Systems (Domain Admin Privilege)
        Relationship(
            id="REL-09",
            source_id="DC-CORP-01",
            target_id="VAULT-BACKUP-01",
            type=RelationshipType.REMOTE_EXECUTION,
            protocol="TCP",
            port=445,
            properties={"method": "WinRM / WMI / SMB Administrator Session"},
        ),
        Relationship(
            id="REL-10",
            source_id="DC-CORP-01",
            target_id="DB-PROD-01",
            type=RelationshipType.PRIVILEGE,
            properties={"privilege": "Domain Controller Backup Delegation"},
        ),
        # App Server to Backup Server (Normal backup channel)
        Relationship(
            id="REL-11",
            source_id="APP-SRV-01",
            target_id="VAULT-BACKUP-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="TCP",
            port=6160,
        ),
        # Cloud Reachability from DevOps
        Relationship(
            id="REL-12",
            source_id="WS-ENG-04",
            target_id="CLOUD-K8S-01",
            type=RelationshipType.REMOTE_EXECUTION,
            protocol="TCP",
            port=6443,
            properties={"auth": "Kubernetes kubeconfig admin token"},
        ),
        # SIEM Log Forwarding
        Relationship(
            id="REL-13",
            source_id="DC-CORP-01",
            target_id="SIEM-SOC-01",
            type=RelationshipType.NETWORK_REACHABILITY,
            protocol="UDP",
            port=514,
        ),
    ]

    stats = {
        "total_assets": len(assets),
        "total_identities": len(identities),
        "total_relationships": len(relationships),
        "total_controls": len([ctrl_edr_fleet, ctrl_waf, ctrl_mfa_corp, ctrl_vault_airgap]),
        "critical_crown_jewels": ["DC-CORP-01", "DB-PROD-01", "VAULT-BACKUP-01"],
        "unprotected_paths_to_crown_jewels": 17,
        "baseline_posture_score": 54.0,  # Out of 100
    }

    return DigitalTwinTopology(
        snapshot_id="snapshot_001",
        version=1,
        timestamp=now,
        name="Corporate Cyber War Room - Ground Truth Baseline",
        assets=assets,
        identities=identities,
        relationships=relationships,
        controls=[ctrl_edr_fleet, ctrl_waf, ctrl_mfa_corp, ctrl_vault_airgap],
        stats=stats,
    )


# Alias for backwards compatibility
create_seed_topology = create_demo_topology

